# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HFXnQlW4hHJGGYhyFRVTX8yL_WZTBwQs
"""

import gradio as gr
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
import warnings

# Bỏ qua các cảnh báo không cần thiết
warnings.filterwarnings('ignore')

# ==========================================
# 1. KHỞI TẠO VÀ HUẤN LUYỆN MÔ HÌNH (CHẠY NGẦM)
# ==========================================
print("Đang nạp dữ liệu và huấn luyện 3 mô hình...")
print("Quá trình này mất khoảng 2-3 giây, vui lòng đợi...")

# Tải dữ liệu
df = pd.read_csv('movie.csv')

# Trích xuất đặc trưng (TF-IDF)
vectorizer = TfidfVectorizer(stop_words='english', max_features=10000)
X_tfidf = vectorizer.fit_transform(df['text'])
y = df['label']

# Huấn luyện 3 mô hình đồng thời
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000).fit(X_tfidf, y),
    "Support Vector Machine (SVM)": LinearSVC(max_iter=2000, random_state=42).fit(X_tfidf, y),
    "Multinomial Naive Bayes": MultinomialNB().fit(X_tfidf, y)
}

print("Huấn luyện thành công! Đang khởi động giao diện...")

# ==========================================
# 2. HÀM XỬ LÝ DỰ ĐOÁN CẢM XÚC
# ==========================================
def predict_sentiment(review_text, model_name):
    # Kiểm tra nếu người dùng chưa nhập gì
    if not review_text.strip():
        return "⚠️ Vui lòng nhập nội dung đánh giá!"

    # Tiền xử lý và Vector hóa câu văn người dùng nhập
    vectorized_text = vectorizer.transform([review_text])

    # Lấy mô hình người dùng đã chọn
    selected_model = models[model_name]

    # Dự đoán
    prediction = selected_model.predict(vectorized_text)[0]

    # Trả về kết quả
    if prediction == 1:
        return "TÍCH CỰC (Positive) 😃👍\n\nKhán giả có trải nghiệm tốt với bộ phim này."
    else:
        return "TIÊU CỰC (Negative) 😞👎\n\nKhán giả không hài lòng hoặc chê bai bộ phim."

# ==========================================
# 3. THIẾT KẾ GIAO DIỆN WEB BẰNG GRADIO
# ==========================================
# Sử dụng Blocks để tùy chỉnh layout đẹp hơn
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    # Tiêu đề ứng dụng
    gr.Markdown("<h1 style='text-align: center;'>🎬 HỆ THỐNG PHÂN TÍCH CẢM XÚC ĐÁNH GIÁ PHIM</h1>")
    gr.Markdown("<p style='text-align: center;'><i>Đồ án môn học - Xây dựng dựa trên Machine Learning & Xử lý ngôn ngữ tự nhiên (NLP)</i></p>")

    with gr.Row():
        # Cột bên trái: Nhập liệu và Chọn mô hình
        with gr.Column(scale=2):
            txt_input = gr.Textbox(
                lines=6,
                placeholder="Nhập nhận xét phim (tiếng Anh) vào đây...\nVí dụ: The acting was brilliant and the story kept me on the edge of my seat!",
                label="📝 Nội dung đánh giá của khách hàng"
            )

            model_choice = gr.Radio(
                choices=list(models.keys()),
                value="Logistic Regression", # Mặc định chọn LR vì độ chính xác cao nhất
                label="⚙️ Chọn Thuật toán Học máy"
            )

            btn_predict = gr.Button("🔍 Bắt đầu Phân tích", variant="primary")

        # Cột bên phải: Hiển thị kết quả
        with gr.Column(scale=1):
            txt_output = gr.Textbox(
                lines=4,
                label="📊 Kết quả Dự đoán",
                interactive=False # Không cho phép người dùng sửa kết quả
            )

    # Xử lý sự kiện khi bấm nút
    btn_predict.click(
        fn=predict_sentiment,
        inputs=[txt_input, model_choice],
        outputs=txt_output
    )

    # Thêm một số ví dụ có sẵn để người dùng click thử nghiệm nhanh
    gr.Markdown("### 💡 Hoặc nhấp thử vào các ví dụ mẫu dưới đây:")
    gr.Examples(
        examples=[
            ["This movie is absolutely a masterpiece! The visuals are stunning and the soundtrack is beautiful.", "Logistic Regression"],
            ["What a complete waste of time. The plot makes no sense and the acting is incredibly wooden.", "Support Vector Machine (SVM)"],
            ["It started out okay but the ending was a huge disappointment.", "Multinomial Naive Bayes"]
        ],
        inputs=[txt_input, model_choice]
    )
# Chạy ứng dụng
if __name__ == "__main__":
    demo.launch(share=False)